# Generated by Django 3.2.3 on 2021-05-20 20:16

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Name')),
                ('model', models.CharField(blank=True, default='', max_length=255, verbose_name='Model')),
                ('manufacturer', models.CharField(blank=True, default='', max_length=255, verbose_name='Manufacturer')),
                ('serial', models.BigIntegerField(unique=True, verbose_name='Serial number')),
                ('password', models.CharField(max_length=255, verbose_name='Password')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Temperature')),
                ('humidity', models.FloatField(verbose_name='Humidity')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
